name: Trigger auto deployment for nino-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/nino-container-app-AutoDeployTrigger-3007c08f-742a-4471-b5b7-aacc72c4b0f1.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NINOCONTAINERAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ninocontainerregistry.azurecr.io
          registryUsername: ${{ secrets.NINOCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NINOCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: nino-container-app
          resourceGroup: rg-container-apps-nino
          imageToBuild: ninocontainerregistry.azurecr.io/nino-container-app:${{ github.sha }}
          
            

     

